org: tmendez
app: express-test
service: express-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: '20201221'
  timeout: 120

functions:
  api:
    handler: index.handler
    environment:
      SENDGRID_API_KEY: ${param:SENDGRID_API_KEY}
      SENDGRID_API_PASS: ${param:SENDGRID_API_PASS}
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
plugins:
  - serverless-http
  